source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
         end
    end
  end
end

target 'iOSDemo' do
  use_frameworks!

    pod 'TPNiOS','6.5.45'
    #TPN Adx SDK(necessary)
    pod 'TPNMediationAdxSmartdigimktAdapter'#,'6.5.42.1'
    pod 'TPNDebugUISDK'

    pod 'AppLovinSDK'
    pod 'OpAdxSdk', '2.11.2'
    pod 'TPNiOSOperaSDKAdapter', '2.11.2.1'


    # Demo UI依赖的第三库
    pod 'Masonry'
    pod 'SDWebImage'
    pod 'MJRefresh'
    pod 'SVProgressHUD'

end
